# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iySx5SWBsn1oU497Duv89ypZ2UP5sZsX
"""

import random
rozdelovac = "-----------------------------------------------"
#Definované uživatelské funkce pro práci s hrou Bulls and Cows
def vygeneruj_nahodne_cislo():
    """
    Funkce generující náhodné čtyřmístné číslo
    """
    nahodne_cislo = list()
    while len(nahodne_cislo) < 4:
      cislicko = random.randint(0, 9)
      if len(nahodne_cislo) == 0 and cislicko == 0:
        continue
      elif len(nahodne_cislo) == 0 and cislicko != 0:
        nahodne_cislo.append(cislicko)
      elif cislicko not in nahodne_cislo:
        nahodne_cislo.append(cislicko)
      else:
        continue
    return list(nahodne_cislo)

def overeni_hracovo_cisla(cislo):
    """
    Funkce ověřující validitu hráčem tipovaného čísla(délka,duplicita,nula,atd)
    """
    if not all(c.isdigit() for c in cislo):
      return "You can use just numbers, try again."
    elif len(cislo) != 4:
      return "There have to be 4 digits, try again."
    elif cislo[0] == '0':
      return "The number can´t start with 0, try again."
    elif len(set(cislo)) != 4:
      return "You can´t use one digit twice, try again."
    else:
      return True

def vypocet_bulls_cows(nahodne_cislo, hracovo_cislo_analyza):
    """
    Funkce porovnávající bulls and cown mezi náhdoným číslem a hráčem zadaným číslem
    Výsledkem jsou počty těchto hodnot
    """
    byci = list()
    kravky = list()
    n = 0
    #Počítání bulls
    while n < 4:
      if nahodne_cislo[n] == hracovo_cislo_analyza[n]:
        byci.append(nahodne_cislo[n])
        n = n + 1
      else:
        n = n + 1
    n = 0
    #Počítání cows
    while n < 4:
      if hracovo_cislo_analyza[n] in byci:
        n = n + 1
      elif hracovo_cislo_analyza[n] in nahodne_cislo:
        kravky.append(hracovo_cislo_analyza[n])
        n = n + 1
      else:
        n = n + 1
    if len(byci) == 4:
      return True

    if len(byci) == 1:
      oznaceni_byci = "bull"
    else:
      oznaceni_byci = "bulls"

    if len(kravky) == 1:
      oznaceni_kravky = "cow"
    else:
      oznaceni_kravky = "cows"
    return f"{len(byci)} {oznaceni_byci}, {len(kravky)} {oznaceni_kravky}"

#Úvod a vygenerování náhodného čísla pomocí funkce k tomu vytvořené
print(f"""Hi there!\n{rozdelovac}\nI've generated a random 4 digit number for you.\n
Let's play a bulls and cows game.\n{rozdelovac}\n""")
nahodne_cislo = vygeneruj_nahodne_cislo()

#Kontrola a zpracoání čísla, které tipuje hráč pomocí funkce
#+ jeho následné porovnání oproti výše vygenerovanému náhodnému číslu pomocí funkce
while True:
    while True:
      hracovo_cislo = list(input("Enter a 4 digit number not starting with 0: "))
      vysledek_kontroly = overeni_hracovo_cisla(hracovo_cislo)
      if vysledek_kontroly is True:
        hracovo_cislo_analyza = [int(c) for c in (hracovo_cislo)]
        break
      else:
        print(vysledek_kontroly)
        print(rozdelovac)

    vysledek_vypoctu = vypocet_bulls_cows(nahodne_cislo, hracovo_cislo_analyza)
    if vysledek_vypoctu is True:
      print(f">>> {int("".join(map(str, hracovo_cislo_analyza)))}")
      print(f"Congratulations, that´s exactly the number I have generated!")
      break
    else:
      print(f">>> {int("".join(map(str, hracovo_cislo_analyza)))}")
      print(vypocet_bulls_cows(nahodne_cislo, hracovo_cislo_analyza))
      print(rozdelovac)